package com.simple.deeplink.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeSpec

/**
 * KSP Symbol Processor chính cho thư viện Deeplink.
 *
 * Processor này chạy tại **compile-time**, quét toàn bộ source code để tìm
 * các class có annotation [@Deeplink][com.simple.deeplink.Deeplink], sau đó
 * tự động sinh ra file `HandlerRegisterImpl.kt` đăng ký tất cả các handler đó
 * vào [DeeplinkResolver][com.simple.deeplink.DeeplinkResolver].
 *
 * ## Luồng hoạt động tổng quan
 * ```
 * Gradle build
 *   → KSP plugin kích hoạt DeeplinkProcessorProvider
 *   → DeeplinkProcessor.process() được gọi
 *   → Tìm tất cả class có @Deeplink
 *   → Validate từng class
 *   → Sinh ra HandlerRegisterImpl.kt
 * ```
 *
 * ## File được sinh ra có dạng
 * ```kotlin
 * // Generated by DeeplinkProcessor. DO NOT EDIT.
 * @AutoRegister(apis = [DeeplinkRegister::class])
 * class HandlerRegisterImpl : DeeplinkRegister {
 *     override fun register() {
 *         DeeplinkResolver.register(ADeeplinkHandler())
 *         DeeplinkResolver.register(BDeeplinkHandler())
 *     }
 * }
 * ```
 *
 * @param codeGenerator Công cụ KSP để tạo và ghi file Kotlin mới.
 * @param logger        Logger để báo lỗi/cảnh báo trong quá trình build.
 *
 * @see DeeplinkProcessorProvider
 * @see com.simple.deeplink.Deeplink
 */
class DeeplinkProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    companion object {
        /** Fully-qualified name của annotation [@Deeplink][com.simple.deeplink.Deeplink]. */
        const val DEEPLINK_ANNOTATION = "com.simple.deeplink.Deeplink"

        /**
         * Fully-qualified name của interface [DeeplinkHandler][com.simple.deeplink.DeeplinkHandler].
         *
         * Dùng để kiểm tra xem class có implement đúng interface không.
         */
        const val DEEPLINK_HANDLER = "com.simple.deeplink.DeeplinkHandler"

        /** Fully-qualified name của interface [DeeplinkRegister][com.simple.deeplink.DeeplinkRegister]. */
        const val DEEPLINK_REGISTER = "com.simple.deeplink.DeeplinkRegister"

        /** Fully-qualified name của object [DeeplinkResolver][com.simple.deeplink.DeeplinkResolver]. */
        const val DEEPLINK_RESOLVER = "com.simple.deeplink.DeeplinkResolver"

        /**
         * Fully-qualified name của annotation
         * [@AutoRegister][com.simple.auto.register.AutoRegister].
         *
         * Annotation này báo cho AutoRegisterManager biết class cần được tự động
         * khởi tạo và đăng ký khi app start.
         */
        const val AUTO_REGISTER = "com.simple.auto.register.AutoRegister"

        /** Tên của class Kotlin được sinh ra. */
        const val GENERATED_CLASS_NAME = "HandlerRegisterImpl"
    }

    // ─── Entry Point ──────────────────────────────────────────────────────────

    /**
     * Điểm vào chính của KSP — được gọi **mỗi round** compile.
     *
     * KSP có thể gọi [process] nhiều lần (multi-round processing) vì một số
     * symbol có thể chưa resolve được ở round đầu (ví dụ: type từ module khác
     * chưa compile xong). Các symbol chưa resolve sẽ được trả về để retry.
     *
     * ## Thứ tự xử lý
     * 1. Lấy tất cả symbol có annotation `@Deeplink`
     * 2. Lọc ra những symbol đã resolve đầy đủ và hợp lệ
     * 3. Nếu có symbol hợp lệ → sinh code
     * 4. Trả về các symbol chưa resolve để KSP retry ở round sau
     *
     * @param resolver Cho phép truy vấn các symbol trong source code hiện tại.
     * @return Danh sách symbol chưa resolve — sẽ được xử lý lại ở round sau.
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(DEEPLINK_ANNOTATION)

        val validHandlers = collectValidHandlers(symbols)

        if (validHandlers.isNotEmpty()) {
            generate(validHandlers)
        }

        // Trả về các symbol chưa resolve được để KSP retry ở round tiếp theo
        return symbols.filterNot { it.validate() }.toList()
    }

    // ─── Collect ──────────────────────────────────────────────────────────────

    /**
     * Lọc ra danh sách các handler class hợp lệ từ tập symbol đầu vào.
     *
     * Một class được đưa vào danh sách kết quả khi thoả mãn **cả 3** điều kiện:
     * 1. Là [KSClassDeclaration] (không phải function, property, type alias, v.v.)
     * 2. Đã được KSP resolve đầy đủ ([KSAnnotated.validate] = `true`)
     * 3. Thoả mãn các ràng buộc business trong [validateHandler]
     *
     * @param symbols Sequence các symbol có annotation `@Deeplink`.
     * @return Danh sách class hợp lệ, sẵn sàng để sinh code.
     */
    private fun collectValidHandlers(symbols: Sequence<KSAnnotated>): List<KSClassDeclaration> {
        return symbols
            .filterIsInstance<KSClassDeclaration>() // Chỉ lấy class declaration
            .filter { it.validate() }               // Bỏ qua symbol chưa resolve xong
            .filter { validateHandler(it) }         // Kiểm tra ràng buộc business
            .toList()
    }

    // ─── Validate ─────────────────────────────────────────────────────────────

    /**
     * Kiểm tra toàn diện xem một class có đủ điều kiện làm Deeplink handler không.
     *
     * Hàm này tổng hợp tất cả các bước validate và trả về `false` ngay khi
     * gặp vi phạm đầu tiên (short-circuit evaluation).
     *
     * @param classDecl Class cần kiểm tra.
     * @return `true` nếu class hợp lệ, `false` nếu vi phạm bất kỳ điều kiện nào.
     */
    private fun validateHandler(classDecl: KSClassDeclaration): Boolean {
        return checkNotAbstractOrSealed(classDecl)
                && checkImplementsDeeplinkHandler(classDecl)
    }

    /**
     * Kiểm tra class không phải abstract hoặc sealed.
     *
     * **Lý do:** Abstract/sealed class không thể khởi tạo trực tiếp bằng `ClassName()`,
     * nên code sinh ra (`DeeplinkResolver.register(XxxHandler())`) sẽ không compile được.
     *
     * @param classDecl Class cần kiểm tra.
     * @return `true` nếu class là concrete class (có thể khởi tạo được).
     */
    private fun checkNotAbstractOrSealed(classDecl: KSClassDeclaration): Boolean {
        val isAbstractOrSealed = Modifier.ABSTRACT in classDecl.modifiers
                || Modifier.SEALED in classDecl.modifiers

        if (isAbstractOrSealed) {
            logger.error(
                "@Deeplink không thể dùng trên abstract/sealed class: ${classDecl.simpleName.asString()}",
                classDecl
            )
        }

        return !isAbstractOrSealed
    }

    /**
     * Kiểm tra class có implement [DeeplinkHandler][com.simple.deeplink.DeeplinkResolver.DeeplinkHandler] không.
     *
     * So sánh bằng [qualifiedName][com.google.devtools.ksp.symbol.KSDeclaration.qualifiedName]
     * thay vì tên đơn giản để tránh nhầm lẫn với các interface cùng tên ở package khác.
     *
     * **Lưu ý:** Chỉ kiểm tra **direct super type** (không đệ quy lên parent).
     * Nếu class extend từ một class trung gian (không annotate @Deeplink) mà class
     * trung gian đó mới implement DeeplinkHandler, check này sẽ fail. Thiết kế này
     * là chủ ý để tránh đăng ký nhầm handler.
     *
     * @param classDecl Class cần kiểm tra.
     * @return `true` nếu class trực tiếp implement [DeeplinkHandler][com.simple.deeplink.DeeplinkResolver.DeeplinkHandler].
     */
    private fun checkImplementsDeeplinkHandler(classDecl: KSClassDeclaration): Boolean {
        val implementsHandler = classDecl.superTypes.any { superTypeRef ->
            val qualifiedName = superTypeRef.resolve().declaration.qualifiedName?.asString()
            qualifiedName == DEEPLINK_HANDLER
        }

        if (!implementsHandler) {
            logger.error(
                "${classDecl.simpleName.asString()} phải implement $DEEPLINK_HANDLER",
                classDecl
            )
        }

        return implementsHandler
    }

    // ─── Generate ─────────────────────────────────────────────────────────────

    /**
     * Điều phối toàn bộ quá trình sinh code từ danh sách handler đã validate.
     *
     * Hàm này đóng vai trò orchestrator: gọi [buildFileSpec] để tạo nội dung,
     * sau đó gọi [writeToFile] để ghi ra disk.
     *
     * @param classDecls Danh sách handler đã được validate, sẽ được đăng ký
     *   trong hàm `register()` của class sinh ra.
     */
    private fun generate(classDecls: List<KSClassDeclaration>) {
        val packageName = classDecls.first().packageName.asString()
        val fileSpec = buildFileSpec(packageName, classDecls)
        writeToFile(fileSpec, packageName, classDecls)
    }

    /**
     * Xây dựng [FileSpec] — đại diện cho toàn bộ nội dung file `.kt` sẽ được sinh.
     *
     * File bao gồm:
     * - Một comment header cảnh báo "DO NOT EDIT"
     * - Class [HandlerRegisterImpl] (xem [buildClassSpec])
     *
     * @param packageName Package của file được sinh ra (lấy từ package của handler đầu tiên).
     * @param classDecls  Danh sách handler để đưa vào body class.
     * @return [FileSpec] sẵn sàng để ghi ra disk.
     */
    private fun buildFileSpec(packageName: String, classDecls: List<KSClassDeclaration>): FileSpec {
        return FileSpec.builder(packageName, GENERATED_CLASS_NAME)
            .addFileComment("Generated by DeeplinkProcessor. DO NOT EDIT.")
            .addType(buildClassSpec(classDecls))
            .build()
    }

    /**
     * Xây dựng [TypeSpec] cho class [HandlerRegisterImpl].
     *
     * Class được sinh ra có cấu trúc:
     * ```kotlin
     * @AutoRegister(apis = [DeeplinkRegister::class])
     * class HandlerRegisterImpl : DeeplinkRegister {
     *     override fun register() { ... }
     * }
     * ```
     *
     * Annotation `@AutoRegister` giúp [AutoRegisterManager][com.simple.auto.register.AutoRegisterManager]
     * tự động tìm thấy và gọi `register()` mà không cần khai báo thủ công.
     *
     * @param classDecls Danh sách handler để đưa vào hàm `register()`.
     * @return [TypeSpec] của class [HandlerRegisterImpl].
     */
    private fun buildClassSpec(classDecls: List<KSClassDeclaration>): TypeSpec {
        val deeplinkRegister = ClassName.bestGuess(DEEPLINK_REGISTER)
        val autoRegister = ClassName.bestGuess(AUTO_REGISTER)

        return TypeSpec.classBuilder(GENERATED_CLASS_NAME)
            .addAnnotation(buildAutoRegisterAnnotation(autoRegister, deeplinkRegister))
            .addSuperinterface(deeplinkRegister)
            .addFunction(buildRegisterFunction(classDecls))
            .build()
    }

    /**
     * Xây dựng [AnnotationSpec] cho `@AutoRegister(apis = [DeeplinkRegister::class])`.
     *
     * Tham số `apis` khai báo interface mà class này implement, giúp
     * [AutoRegisterManager][com.simple.auto.register.AutoRegisterManager] biết
     * phải subscribe theo key nào để tìm ra [HandlerRegisterImpl] khi app khởi động.
     *
     * @param autoRegister    ClassName của `@AutoRegister`.
     * @param deeplinkRegister ClassName của [DeeplinkRegister][com.simple.deeplink.DeeplinkRegister].
     * @return [AnnotationSpec] đã build xong.
     */
    private fun buildAutoRegisterAnnotation(
        autoRegister: ClassName,
        deeplinkRegister: ClassName,
    ): AnnotationSpec {
        return AnnotationSpec.builder(autoRegister)
            .addMember("apis = [%T::class]", deeplinkRegister)
            .build()
    }

    /**
     * Xây dựng hàm `register()` — override từ [DeeplinkRegister][com.simple.deeplink.DeeplinkRegister].
     *
     * Với mỗi handler trong [classDecls], hàm sẽ sinh một câu lệnh:
     * ```kotlin
     * DeeplinkResolver.register(XxxHandler())
     * ```
     *
     * Thứ tự đăng ký = thứ tự KSP trả về (thường là thứ tự khai báo trong source).
     * Thứ tự này ảnh hưởng đến priority khi nhiều handler cùng `canHandle()` trả về `true`
     * — handler đăng ký trước sẽ được dùng trước.
     *
     * @param classDecls Danh sách handler cần đăng ký, theo thứ tự ưu tiên.
     * @return [FunSpec] của hàm `register()`.
     */
    private fun buildRegisterFunction(classDecls: List<KSClassDeclaration>): FunSpec {
        val deeplinkResolver = ClassName.bestGuess(DEEPLINK_RESOLVER)

        return FunSpec.builder("register")
            .addModifiers(KModifier.OVERRIDE)
            .apply {
                classDecls.forEach { classDecl ->
                    val handlerClass = ClassName(
                        classDecl.packageName.asString(),
                        classDecl.simpleName.asString()
                    )
                    // Sinh câu lệnh: DeeplinkResolver.register(XxxHandler())
                    addStatement("%T.register(%T())", deeplinkResolver, handlerClass)
                }
            }
            .build()
    }

    /**
     * Ghi [FileSpec] ra file `.kt` thực tế trên disk thông qua [codeGenerator].
     *
     * ## Về Dependencies với `aggregating = true`
     * Khi `aggregating = true`, KSP biết rằng file sinh ra này phụ thuộc vào
     * **tất cả** source file chứa handler. Nghĩa là nếu **bất kỳ** file nào
     * thêm/xoá/sửa một `@Deeplink` class, toàn bộ file sinh ra sẽ được tái sinh.
     *
     * Nếu dùng `aggregating = false` (isolating), KSP chỉ tái sinh khi file
     * được truyền vào `sources` thay đổi — không phù hợp vì file này tổng hợp
     * từ nhiều nguồn.
     *
     * @param fileSpec    FileSpec đã build, chứa nội dung cần ghi.
     * @param packageName Package của file sinh ra — dùng để xác định đường dẫn.
     * @param classDecls  Danh sách handler — dùng để tính [Dependencies].
     */
    private fun writeToFile(
        fileSpec: FileSpec,
        packageName: String,
        classDecls: List<KSClassDeclaration>,
    ) {
        val dependencies = Dependencies(
            aggregating = true,
            *classDecls.mapNotNull { it.containingFile }.toTypedArray()
        )

        codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = packageName,
            fileName = GENERATED_CLASS_NAME
        ).bufferedWriter().use { writer ->
            fileSpec.writeTo(writer)
        }
    }
}
